name: Node JS build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: index
          path: index

      - name: Install netlify cli
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod \
          -- dir=.  \
            --site ${{ secrets.NELIFY_SITE_ID }} \
            --auth ${{ secrets.NELIFY_API_TOKEN }}